# Site settings
author: Sardar Hamza Naqi
title: Why Software Engineering?
header-img: img/home-bg.png
email: sardarhamzanaqi@gmail.com
copyright_name: Sardar Hamza Naqi
description: > # this means to ignore newlines until "baseurl:"
  Why now?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hamza15

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
